import { defineField, defineType } from 'sanity'

export const modeloType = defineType({
  name: 'modelo',
  title: 'Modelos',
  type: 'document',
  fields: [
    defineField({
      name: 'nombre',
      title: 'Nombre del modelo',
      type: 'string',
      validation: (r) => r.required(),
    }),
    defineField({
      name: 'slug',
      title: 'URL del modelo',
      type: 'slug',
      options: { source: 'nombre' },
      validation: (r) => r.required(),
    }),
    defineField({
      name: 'categoria',
      title: 'Categoría',
      description: 'Categoría física del vehículo (siempre la real, ej. un sedán híbrido sigue siendo "Sedanes & Hatchbacks"). No usar "Híbridos Eléctricos" aquí — para eso existe el campo "¿Es híbrido o eléctrico?" de abajo, que funciona como filtro adicional, no como categoría excluyente.',
      type: 'string',
      options: {
        list: [
          'Sedanes & Hatchbacks',
          "Suv's & Minivans",
          "Pickup's & Comerciales",
          'Toyota Gazoo Racing',
        ],
        layout: 'radio',
      },
      validation: (r) => r.required(),
    }),
    defineField({
      name: 'esHibridoElectrico',
      title: '¿Es híbrido o eléctrico? (HEV / PHEV / EV)',
      description: 'Marca este campo para que el modelo aparezca también en el filtro "Híbridos Eléctricos (HEV y PHEV)" de /modelos, además de su categoría física normal. No afecta la categoría del modelo.',
      type: 'boolean',
      initialValue: false,
    }),
    defineField({
      name: 'anio',
      title: 'Año del modelo (ej: 2026)',
      type: 'number',
      validation: (r) => r.required().min(2020).max(2035),
      group: 'detalle',
    }),
    defineField({
      name: 'precioDesde',
      title: 'Precio desde (MXN)',
      type: 'number',
      validation: (r) => r.required().min(0),
    }),
    defineField({
      name: 'imagenTarjeta',
      title: 'Imagen de tarjeta (catálogo y "Modelos similares")',
      description: 'Se usa como miniatura al listar el modelo — no aparece en el Hero de su propia página, ese es un campo aparte.',
      type: 'image',
      options: { hotspot: true },
      validation: (r) => r.required(),
    }),
    defineField({
      name: 'descripcionCorta',
      title: 'Descripción corta (para tarjetas)',
      type: 'text',
      rows: 2,
      validation: (r) => r.max(160),
    }),
    defineField({
      name: 'descripcion',
      title: 'Texto introductorio (debajo del Hero)',
      description: 'Párrafo de presentación del modelo, justo debajo del Hero.',
      type: 'array',
      of: [{ type: 'block' }],
    }),
    defineField({
      name: 'caracteristicas',
      title: 'Barra de datos destacados (debajo del Hero)',
      description:
        'Ej: Motor, Pasajeros, Tracción, Tecnología — cada modelo puede tener datos distintos (una pick-up podría usar "Capacidad de carga" en vez de "Pasajeros").',
      type: 'array',
      of: [
        {
          type: 'object',
          fields: [
            {
              name: 'icono',
              title: 'Ícono',
              type: 'string',
              description:
                'Set de íconos de marca ya diseñados en código (components/ui/HighlightIcon.tsx). Si necesitas un concepto que no está en la lista, pídelo antes de usar uno parecido.',
              options: {
                list: [
                  { title: 'Motor', value: 'motor' },
                  { title: 'Pasajeros', value: 'pasajeros' },
                  { title: 'Tracción', value: 'traccion' },
                  { title: 'Tecnología', value: 'tecnologia' },
                  { title: 'Capacidad de carga', value: 'capacidad-carga' },
                  { title: 'Potencia', value: 'potencia' },
                  { title: 'Autonomía', value: 'autonomia' },
                  { title: 'Remolque', value: 'remolque' },
                  { title: 'Transmisión', value: 'transmision' },
                  { title: 'Maletero / cajuela', value: 'maletero' },
                  { title: 'Rendimiento de combustible', value: 'rendimiento' },
                ],
              },
            },
            { name: 'titulo', title: 'Título (ej: Motor)', type: 'string' },
            { name: 'valor', title: 'Valor (ej: 2.0L · 168 HP)', type: 'string' },
          ],
          preview: {
            select: { title: 'titulo', subtitle: 'valor' },
          },
        },
      ],
    }),
    defineField({
      name: 'destacado',
      title: '¿Mostrar en homepage?',
      type: 'boolean',
      initialValue: false,
    }),
    defineField({
      name: 'orden',
      title: 'Orden en el catálogo',
      type: 'number',
      initialValue: 99,
    }),
    defineField({
      name: 'seoTitulo',
      title: 'SEO: Título (deja vacío para usar el nombre)',
      type: 'string',
      group: 'seo',
    }),
    defineField({
      name: 'seoDescripcion',
      title: 'SEO: Descripción',
      type: 'text',
      rows: 2,
      validation: (r) => r.max(160),
      group: 'seo',
    }),
    defineField({
      name: 'heroDesktop',
      title: 'Hero (escritorio)',
      type: 'image',
      options: { hotspot: true },
      group: 'detalle',
    }),
    defineField({
      name: 'heroMobile',
      title: 'Hero (móvil)',
      type: 'image',
      group: 'detalle',
    }),
    defineField({
      name: 'heroSubtitulo',
      title: 'Frase bajo el nombre (Hero)',
      description: 'Ej: "El sedán más vendido del mundo. Por algo será."',
      type: 'text',
      rows: 2,
      group: 'secciones',
    }),
    defineField({
      name: 'versiones',
      title: 'Versiones y precios',
      type: 'array',
      group: 'detalle',
      of: [
        {
          type: 'object',
          name: 'version',
          fields: [
            { name: 'nombre', title: 'Nombre (ej: LE CVT)', type: 'string', validation: (r) => r.required() },
            { name: 'precio', title: 'Precio (MXN)', type: 'number', validation: (r) => r.required().min(0) },
            { name: 'imagen', title: 'Imagen de la versión', type: 'image', options: { hotspot: true } },
            {
              name: 'caracteristicas',
              title: 'Características',
              type: 'array',
              of: [{ type: 'string' }],
            },
          ],
          preview: {
            select: { title: 'nombre', subtitle: 'precio', media: 'imagen' },
          },
        },
      ],
    }),
    defineField({
      name: 'versionesTexto',
      title: 'Texto breve de sección "Versiones"',
      description: 'Frase corta debajo de "Elige tu versión", ~100-120 caracteres.',
      type: 'text',
      rows: 2,
      validation: (r) => r.max(160),
      group: 'secciones',
    }),
    defineField({
      name: 'coloresExterior',
      title: 'Colores y visor 360°',
      type: 'array',
      group: 'detalle',
      of: [
        {
          type: 'object',
          fields: [
            { name: 'label', title: 'Nombre del color', type: 'string', validation: (r) => r.required() },
            { name: 'hex', title: 'Color (hex, para el swatch)', type: 'string', validation: (r) => r.required() },
            { name: 'necesitaBorde', title: '¿Necesita borde en el swatch?', type: 'boolean', initialValue: false },
            {
              name: 'imagenes360',
              title: 'Imágenes del giro (en orden)',
              type: 'array',
              of: [{ type: 'image' }],
            },
          ],
          preview: {
            select: { title: 'label' },
          },
        },
      ],
    }),
    defineField({
      name: 'exteriorTitulo',
      title: 'Título de sección "Exterior"',
      description: 'Ej: "Diseño que impone"',
      type: 'string',
      group: 'secciones',
    }),
    defineField({
      name: 'exteriorTexto',
      title: 'Texto breve de sección "Exterior"',
      description: 'Frase corta debajo del título de Exterior, ~100-120 caracteres.',
      type: 'text',
      rows: 2,
      validation: (r) => r.max(160),
      group: 'secciones',
    }),
    defineField({
      name: 'imagenDestacado',
      title: 'Imagen del destacado (ej: Tecnología / Safety Sense)',
      type: 'image',
      options: { hotspot: true },
      group: 'detalle',
    }),
    defineField({
      name: 'destacadoEyebrow',
      title: 'Etiqueta del destacado',
      description: 'Ej: "Tecnología" — puede variar por modelo, no siempre es tecnología.',
      type: 'string',
      group: 'secciones',
    }),
    defineField({
      name: 'destacadoTitulo',
      title: 'Título del destacado',
      description: 'Ej: "Toyota Safety Sense"',
      type: 'string',
      group: 'secciones',
    }),
    defineField({
      name: 'destacadoTexto',
      title: 'Texto del destacado',
      type: 'text',
      rows: 4,
      group: 'secciones',
    }),
    defineField({
      name: 'seguridadTitulo',
      title: 'Título de sección "Seguridad"',
      description: 'Ej: "Seguridad es mi segundo nombre"',
      type: 'string',
      group: 'secciones',
    }),
    defineField({
      name: 'seguridadTexto',
      title: 'Texto de sección "Seguridad"',
      type: 'text',
      rows: 3,
      group: 'secciones',
    }),
    defineField({
      name: 'seguridadItems',
      title: 'Elementos de seguridad (lista)',
      description: 'Ej: "8 bolsas de aire", "Frenos ABS + EBD" — el número de elementos puede variar por modelo.',
      type: 'array',
      of: [{ type: 'string' }],
      group: 'secciones',
    }),
    defineField({
      name: 'galeriaExteriorDetalle',
      title: 'Galería exterior',
      type: 'array',
      group: 'detalle',
      of: [{ type: 'image', options: { hotspot: true } }],
    }),
    defineField({
      name: 'galeriaInteriorDetalle',
      title: 'Galería interior',
      type: 'array',
      group: 'detalle',
      of: [{ type: 'image', options: { hotspot: true } }],
    }),
    defineField({
      name: 'galeriaTitulo',
      title: 'Título de sección "Galería"',
      description: 'Ej: "El auto más vendido del mundo"',
      type: 'string',
      group: 'secciones',
    }),
    defineField({
      name: 'galeriaTexto',
      title: 'Texto breve de sección "Galería"',
      description: 'Frase corta debajo del título de Galería, ~100-120 caracteres.',
      type: 'text',
      rows: 2,
      validation: (r) => r.max(160),
      group: 'secciones',
    }),
    defineField({
      name: 'imagenRendimiento',
      title: 'Imagen de rendimiento',
      type: 'image',
      options: { hotspot: true },
      group: 'detalle',
    }),
    defineField({
      name: 'rendimientoEyebrow',
      title: 'Etiqueta de sección "Rendimiento"',
      description: 'Ej: "Modo Ahorro" — en un eléctrico podría ser "Autonomía y Carga".',
      type: 'string',
      group: 'secciones',
    }),
    defineField({
      name: 'rendimientoTitulo',
      title: 'Título de sección "Rendimiento"',
      description: 'Ej: "Muévete, ahorra y contribuye"',
      type: 'string',
      group: 'secciones',
    }),
    defineField({
      name: 'rendimientoTexto',
      title: 'Texto de sección "Rendimiento"',
      type: 'text',
      rows: 3,
      group: 'secciones',
    }),
    defineField({
      name: 'rendimientoFilas',
      title: 'Tabla de rendimiento (filas)',
      description:
        'Ej: Transmisión "CVT" con valor "19.14 KM/L". El número de filas y las unidades pueden variar por modelo.',
      type: 'array',
      group: 'secciones',
      of: [
        {
          type: 'object',
          fields: [
            { name: 'transmision', title: 'Transmisión (ej: CVT, HEV)', type: 'string', validation: (r) => r.required() },
            { name: 'valor', title: 'Valor (ej: 19.14)', type: 'string', validation: (r) => r.required() },
            { name: 'unidad', title: 'Unidad (ej: KM/L)', type: 'string', initialValue: 'KM/L' },
          ],
          preview: {
            select: { title: 'transmision', subtitle: 'valor' },
          },
        },
      ],
    }),
  ],
  groups: [
    { name: 'seo', title: 'SEO' },
    { name: 'detalle', title: 'Detalle de página (versiones, 360°, galería)' },
    { name: 'secciones', title: 'Textos de sección (exterior, destacado, seguridad, galería, rendimiento)' },
  ],
  orderings: [
    {
      title: 'Orden manual',
      name: 'ordenAsc',
      by: [{ field: 'orden', direction: 'asc' }],
    },
  ],
  preview: {
    select: {
      title: 'nombre',
      subtitle: 'categoria',
      media: 'imagenTarjeta',
    },
  },
})
